//不懂可以去看看电商项目的p204


export default[
    {
        path: '/',
        redirect: '/home'
    },
    {
        path:'/home',
        component:()=>import('../views/home/Home'),
        redirect:'/home/discover',
        children:[
            {
                path:'/home/discover',
                component:()=>import('../views/discover/Discover'),
                redirect:'/home/discover/person',
                children:[
                    {
                        path:'/home/discover/person',
                        name:'person',
                        component:()=>import('../views/discover/children/Person')
                    },
                    {
                        path:'/home/discover/musiclist',
                        name:'musiclist',
                        component:()=>import('../views/discover/children/MusicList'),
                        redirect:'/home/discover/musiclist/musiclistindex',
                        children:[
                            {
                                path:'/home/discover/musiclist/musiclistindex',
                                name:'musiclistindex',
                                component:()=>import('../views/discover/children/music-children/MusicListIndex')
                            }
                        ]
                    },
                    {
                        path:'/home/discover/ranking',
                        component:()=>import('../views/discover/children/Ranking')
                    },
                    {
                        path:'/home/discover/singer',
                        component:()=>import('../views/discover/children/Singer')
                    }
                ]
            },
            {
                path:'/home/video',
                component:()=>import('../views/video/Video'),
                redirect:'/home/video/videolist',
                children:[
                    {
                        path:'/home/video/videolist',
                        component:()=>import('../views/video/videoChildren/VideoList')
                    },
                    {
                        path:'/home/video/mvlist',
                        component:()=>import('../views/video//videoChildren/MvList')
                    }
                ],
            },
            {
                path:'/home/favorite',
                component:()=>import('../views/favorite/Favorite')
            },
            {
                path:'/home/recommend',
                component:()=>import('../views/recommend/Recommend')
            },
            {
                path:"/home/musiclistdetail/:id",
                name:'musicListDetail',
                component:()=>import('../views/musicListDetail/MusicListDetail')
            }
        ]
    }
]